<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_gaming</name>
   <tag></tag>
   <elementGuidId>6f3b3d12-d56d-49ca-9a7c-ee2a53ebce41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-1144-1']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#list-item-1144-1 > div.v-list-item__content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fc712236-d7b0-4289-ace9-56a377b5c11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__content</value>
      <webElementGuid>eef48817-90f2-4df7-b4a0-a5e222ec36ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>gaming</value>
      <webElementGuid>07905c2a-645d-48d0-bbe1-e8faf29e2b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-1144-1&quot;)/div[@class=&quot;v-list-item__content&quot;]</value>
      <webElementGuid>5005d959-5a43-453f-86be-ebd77857ece2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-1144-1']/div</value>
      <webElementGuid>c1e6e245-ba55-4b60-b53e-f71807195dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gaming'])[2]/following::div[2]</value>
      <webElementGuid>6dd4f301-ba64-4a1a-8252-62805a3b7876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli'])[362]/following::div[7]</value>
      <webElementGuid>e045b38a-0cc4-4c25-b44f-1cdadab80872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gaming'])[4]/preceding::div[2]</value>
      <webElementGuid>814a7289-8d11-4010-b04b-156e50f05b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>f7ad35c7-a170-4668-83ee-2008d471fae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'gaming' or . = 'gaming')]</value>
      <webElementGuid>d7fec7b4-b287-492c-806c-eef3c67c9f61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
